export interface Institution {
  name: string;
  city: string;
  state: string;
}

export const MEDICAL_COLLEGES: Institution[] = [
  // AIIMS Campuses
  { name: "AIIMS New Delhi", city: "New Delhi", state: "Delhi" },
  { name: "AIIMS Bhopal", city: "Bhopal", state: "Madhya Pradesh" },
  { name: "AIIMS Bhubaneswar", city: "Bhubaneswar", state: "Odisha" },
  { name: "AIIMS Jodhpur", city: "Jodhpur", state: "Rajasthan" },
  { name: "AIIMS Patna", city: "Patna", state: "Bihar" },
  { name: "AIIMS Raipur", city: "Raipur", state: "Chhattisgarh" },
  { name: "AIIMS Rishikesh", city: "Rishikesh", state: "Uttarakhand" },
  { name: "AIIMS Nagpur", city: "Nagpur", state: "Maharashtra" },
  { name: "AIIMS Mangalagiri", city: "Mangalagiri", state: "Andhra Pradesh" },
  { name: "AIIMS Gorakhpur", city: "Gorakhpur", state: "Uttar Pradesh" },
  { name: "AIIMS Kalyani", city: "Kalyani", state: "West Bengal" },
  { name: "AIIMS Bilaspur", city: "Bilaspur", state: "Himachal Pradesh" },
  { name: "AIIMS Deoghar", city: "Deoghar", state: "Jharkhand" },
  { name: "AIIMS Guwahati", city: "Guwahati", state: "Assam" },
  { name: "AIIMS Rajkot", city: "Rajkot", state: "Gujarat" },
  // Delhi
  { name: "Maulana Azad Medical College (MAMC)", city: "New Delhi", state: "Delhi" },
  { name: "Lady Hardinge Medical College", city: "New Delhi", state: "Delhi" },
  { name: "Vardhman Mahavir Medical College (VMMC) & Safdarjung Hospital", city: "New Delhi", state: "Delhi" },
  { name: "University College of Medical Sciences (UCMS)", city: "New Delhi", state: "Delhi" },
  { name: "Armed Forces Medical College (AFMC)", city: "Pune", state: "Maharashtra" },
  // Maharashtra
  { name: "Seth GS Medical College & KEM Hospital", city: "Mumbai", state: "Maharashtra" },
  { name: "Grant Medical College & Sir JJ Hospital", city: "Mumbai", state: "Maharashtra" },
  { name: "Topiwala National Medical College (TNM) & BYL Nair Hospital", city: "Mumbai", state: "Maharashtra" },
  { name: "Lokmanya Tilak Municipal Medical College (LTMMC)", city: "Mumbai", state: "Maharashtra" },
  { name: "BJ Medical College", city: "Pune", state: "Maharashtra" },
  { name: "Government Medical College Nagpur", city: "Nagpur", state: "Maharashtra" },
  { name: "Government Medical College Aurangabad", city: "Aurangabad", state: "Maharashtra" },
  { name: "Government Medical College Latur", city: "Latur", state: "Maharashtra" },
  { name: "D Y Patil Medical College", city: "Pune", state: "Maharashtra" },
  { name: "Bharati Vidyapeeth Medical College", city: "Pune", state: "Maharashtra" },
  // Tamil Nadu
  { name: "Madras Medical College (MMC)", city: "Chennai", state: "Tamil Nadu" },
  { name: "Stanley Medical College", city: "Chennai", state: "Tamil Nadu" },
  { name: "Kilpauk Medical College", city: "Chennai", state: "Tamil Nadu" },
  { name: "Coimbatore Medical College", city: "Coimbatore", state: "Tamil Nadu" },
  { name: "Government Medical College Madurai", city: "Madurai", state: "Tamil Nadu" },
  { name: "Thanjavur Medical College", city: "Thanjavur", state: "Tamil Nadu" },
  { name: "Sri Ramachandra Institute of Higher Education", city: "Chennai", state: "Tamil Nadu" },
  { name: "SRM Medical College Hospital & Research Centre", city: "Chennai", state: "Tamil Nadu" },
  { name: "Saveetha Medical College", city: "Chennai", state: "Tamil Nadu" },
  // JIPMER
  { name: "Jawaharlal Institute of PG Medical Education (JIPMER)", city: "Puducherry", state: "Puducherry" },
  // Vellore
  { name: "Christian Medical College (CMC) Vellore", city: "Vellore", state: "Tamil Nadu" },
  // Karnataka
  { name: "Mysore Medical College & Research Institute", city: "Mysuru", state: "Karnataka" },
  { name: "Bangalore Medical College & Research Institute (BMCRI)", city: "Bengaluru", state: "Karnataka" },
  { name: "MS Ramaiah Medical College", city: "Bengaluru", state: "Karnataka" },
  { name: "St. John's Medical College", city: "Bengaluru", state: "Karnataka" },
  { name: "Manipal College of Medical Sciences", city: "Manipal", state: "Karnataka" },
  { name: "Kasturba Medical College Mangalore", city: "Mangaluru", state: "Karnataka" },
  { name: "Kasturba Medical College Manipal", city: "Manipal", state: "Karnataka" },
  { name: "JSS Medical College", city: "Mysuru", state: "Karnataka" },
  { name: "KIMS Medical College", city: "Hubballi", state: "Karnataka" },
  // Andhra Pradesh / Telangana
  { name: "Osmania Medical College", city: "Hyderabad", state: "Telangana" },
  { name: "Gandhi Medical College", city: "Hyderabad", state: "Telangana" },
  { name: "Kakatiya Medical College", city: "Warangal", state: "Telangana" },
  { name: "Rangaraya Medical College", city: "Kakinada", state: "Andhra Pradesh" },
  { name: "Andhra Medical College", city: "Visakhapatnam", state: "Andhra Pradesh" },
  { name: "Guntur Medical College", city: "Guntur", state: "Andhra Pradesh" },
  { name: "Kurnool Medical College", city: "Kurnool", state: "Andhra Pradesh" },
  // Kerala
  { name: "Government Medical College Thiruvananthapuram", city: "Thiruvananthapuram", state: "Kerala" },
  { name: "Government Medical College Kozhikode", city: "Kozhikode", state: "Kerala" },
  { name: "Government Medical College Thrissur", city: "Thrissur", state: "Kerala" },
  { name: "Amrita Institute of Medical Sciences", city: "Kochi", state: "Kerala" },
  { name: "Jubilee Mission Medical College", city: "Thrissur", state: "Kerala" },
  // West Bengal
  { name: "Medical College Kolkata", city: "Kolkata", state: "West Bengal" },
  { name: "RG Kar Medical College", city: "Kolkata", state: "West Bengal" },
  { name: "NRS Medical College", city: "Kolkata", state: "West Bengal" },
  { name: "Calcutta National Medical College", city: "Kolkata", state: "West Bengal" },
  { name: "Midnapore Medical College", city: "Midnapore", state: "West Bengal" },
  // Uttar Pradesh
  { name: "King George's Medical University (KGMU)", city: "Lucknow", state: "Uttar Pradesh" },
  { name: "Motilal Nehru Medical College", city: "Prayagraj", state: "Uttar Pradesh" },
  { name: "Government Medical College BHU (IMS-BHU)", city: "Varanasi", state: "Uttar Pradesh" },
  { name: "Lala Lajpat Rai Memorial Medical College", city: "Meerut", state: "Uttar Pradesh" },
  { name: "Sarojini Naidu Medical College", city: "Agra", state: "Uttar Pradesh" },
  { name: "Rohilkhand Medical College", city: "Bareilly", state: "Uttar Pradesh" },
  // Rajasthan
  { name: "SMS Medical College Jaipur", city: "Jaipur", state: "Rajasthan" },
  { name: "Dr SN Medical College Jodhpur", city: "Jodhpur", state: "Rajasthan" },
  { name: "RNT Medical College Udaipur", city: "Udaipur", state: "Rajasthan" },
  // Punjab / Haryana / Chandigarh
  { name: "PGIMER Chandigarh", city: "Chandigarh", state: "Chandigarh" },
  { name: "Government Medical College Amritsar", city: "Amritsar", state: "Punjab" },
  { name: "Government Medical College Patiala", city: "Patiala", state: "Punjab" },
  { name: "Pt BD Sharma PGIMS Rohtak", city: "Rohtak", state: "Haryana" },
  // Madhya Pradesh
  { name: "Gandhi Medical College Bhopal", city: "Bhopal", state: "Madhya Pradesh" },
  { name: "MGM Medical College Indore", city: "Indore", state: "Madhya Pradesh" },
  { name: "GR Medical College Gwalior", city: "Gwalior", state: "Madhya Pradesh" },
  // Bihar
  { name: "Patna Medical College & Hospital (PMCH)", city: "Patna", state: "Bihar" },
  { name: "Darbhanga Medical College", city: "Darbhanga", state: "Bihar" },
  // Odisha
  { name: "SCB Medical College & Hospital", city: "Cuttack", state: "Odisha" },
  { name: "MKCG Medical College", city: "Berhampur", state: "Odisha" },
  // Gujarat
  { name: "BJ Medical College Ahmedabad", city: "Ahmedabad", state: "Gujarat" },
  { name: "Government Medical College Surat", city: "Surat", state: "Gujarat" },
  { name: "Government Medical College Vadodara", city: "Vadodara", state: "Gujarat" },
  // Assam
  { name: "Gauhati Medical College & Hospital", city: "Guwahati", state: "Assam" },
  { name: "Silchar Medical College", city: "Silchar", state: "Assam" },
  // Himachal Pradesh
  { name: "Indira Gandhi Medical College Shimla", city: "Shimla", state: "Himachal Pradesh" },
  // J&K
  { name: "Government Medical College Jammu", city: "Jammu", state: "Jammu & Kashmir" },
  { name: "Government Medical College Srinagar", city: "Srinagar", state: "Jammu & Kashmir" },
  // Jharkhand
  { name: "Rajendra Institute of Medical Sciences (RIMS)", city: "Ranchi", state: "Jharkhand" },
  // Chhattisgarh
  { name: "PT JNM Medical College Raipur", city: "Raipur", state: "Chhattisgarh" },
  // Goa
  { name: "Goa Medical College", city: "Panaji", state: "Goa" },
  // Tripura
  { name: "Agartala Government Medical College", city: "Agartala", state: "Tripura" },
  // Uttarakhand
  { name: "Government Medical College Haldwani", city: "Haldwani", state: "Uttarakhand" },
  // Private Institutions
  { name: "Amrita Institute of Medical Sciences Chennai", city: "Chennai", state: "Tamil Nadu" },
  { name: "Apollo Institute of Medical Sciences", city: "Hyderabad", state: "Telangana" },
  { name: "Narayana Medical College", city: "Nellore", state: "Andhra Pradesh" },
  { name: "Sri Devaraj Urs Medical College", city: "Kolar", state: "Karnataka" },
  { name: "Yenepoya Medical College", city: "Mangaluru", state: "Karnataka" },
  { name: "Father Muller Medical College", city: "Mangaluru", state: "Karnataka" },
  { name: "Pondicherry Institute of Medical Sciences", city: "Puducherry", state: "Puducherry" },
  { name: "Meenakshi Medical College", city: "Chennai", state: "Tamil Nadu" },
  { name: "Sree Balaji Medical College", city: "Chennai", state: "Tamil Nadu" },
  { name: "PSG Institute of Medical Sciences", city: "Coimbatore", state: "Tamil Nadu" },
  { name: "Chettinad Hospital & Research Institute", city: "Chennai", state: "Tamil Nadu" },
  { name: "Sri Manakula Vinayagar Medical College", city: "Puducherry", state: "Puducherry" },
];

export const HOSPITALS: Institution[] = [
  // Government / Apex
  { name: "AIIMS Delhi (Hospital)", city: "New Delhi", state: "Delhi" },
  { name: "Safdarjung Hospital", city: "New Delhi", state: "Delhi" },
  { name: "RML Hospital (Ram Manohar Lohia)", city: "New Delhi", state: "Delhi" },
  { name: "GTB Hospital (Guru Teg Bahadur)", city: "New Delhi", state: "Delhi" },
  { name: "LNJP Hospital", city: "New Delhi", state: "Delhi" },
  { name: "Lok Nayak Hospital", city: "New Delhi", state: "Delhi" },
  { name: "PGIMER Chandigarh Hospital", city: "Chandigarh", state: "Chandigarh" },
  { name: "CMC Vellore Hospital", city: "Vellore", state: "Tamil Nadu" },
  { name: "KGMU Hospital Lucknow", city: "Lucknow", state: "Uttar Pradesh" },
  { name: "KEM Hospital Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "JJ Hospital Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Nair Hospital Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Sion Hospital Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Sassoon General Hospital Pune", city: "Pune", state: "Maharashtra" },
  { name: "Tata Memorial Hospital", city: "Mumbai", state: "Maharashtra" },
  { name: "Bombay Hospital & Medical Research Centre", city: "Mumbai", state: "Maharashtra" },
  { name: "NIMHANS Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "Victoria Hospital Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "Bowring & Lady Curzon Hospital", city: "Bengaluru", state: "Karnataka" },
  { name: "Rajiv Gandhi Government General Hospital Chennai", city: "Chennai", state: "Tamil Nadu" },
  { name: "Government Stanley Hospital Chennai", city: "Chennai", state: "Tamil Nadu" },
  { name: "Government Kilpauk Medical College Hospital", city: "Chennai", state: "Tamil Nadu" },
  { name: "Osmania General Hospital Hyderabad", city: "Hyderabad", state: "Telangana" },
  { name: "Gandhi Hospital Hyderabad", city: "Hyderabad", state: "Telangana" },
  { name: "Nizams Institute of Medical Sciences (NIMS)", city: "Hyderabad", state: "Telangana" },
  { name: "SCB Medical College Hospital Cuttack", city: "Cuttack", state: "Odisha" },
  { name: "Medical College Hospital Kolkata", city: "Kolkata", state: "West Bengal" },
  { name: "RG Kar Medical College Hospital", city: "Kolkata", state: "West Bengal" },
  { name: "NRS Medical College Hospital", city: "Kolkata", state: "West Bengal" },
  { name: "SSKM Hospital Kolkata", city: "Kolkata", state: "West Bengal" },
  { name: "SMS Hospital Jaipur", city: "Jaipur", state: "Rajasthan" },
  { name: "BJ Medical College Hospital Ahmedabad", city: "Ahmedabad", state: "Gujarat" },
  { name: "Civil Hospital Ahmedabad", city: "Ahmedabad", state: "Gujarat" },
  { name: "Gauhati Medical College Hospital", city: "Guwahati", state: "Assam" },
  { name: "RIMS Hospital Ranchi", city: "Ranchi", state: "Jharkhand" },
  { name: "PMCH Hospital Patna", city: "Patna", state: "Bihar" },
  { name: "Goa Medical College Hospital", city: "Panaji", state: "Goa" },
  { name: "Government Medical College Hospital Thiruvananthapuram (SAT)", city: "Thiruvananthapuram", state: "Kerala" },
  { name: "Government Medical College Hospital Kozhikode", city: "Kozhikode", state: "Kerala" },
  // Apollo Group
  { name: "Apollo Hospitals Chennai", city: "Chennai", state: "Tamil Nadu" },
  { name: "Apollo Hospitals Delhi", city: "New Delhi", state: "Delhi" },
  { name: "Apollo Hospitals Hyderabad", city: "Hyderabad", state: "Telangana" },
  { name: "Apollo Hospitals Kolkata", city: "Kolkata", state: "West Bengal" },
  { name: "Apollo Hospitals Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "Apollo Hospitals Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Apollo Hospitals Ahmedabad", city: "Ahmedabad", state: "Gujarat" },
  { name: "Apollo Hospitals Bhubaneswar", city: "Bhubaneswar", state: "Odisha" },
  // Fortis Group
  { name: "Fortis Hospital Gurgaon", city: "Gurugram", state: "Haryana" },
  { name: "Fortis Hospital Noida", city: "Noida", state: "Uttar Pradesh" },
  { name: "Fortis Hospital Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Fortis Hospital Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "Fortis Hospital Mohali", city: "Mohali", state: "Punjab" },
  { name: "Fortis Hospital Kolkata", city: "Kolkata", state: "West Bengal" },
  // Max Group
  { name: "Max Super Speciality Hospital Saket Delhi", city: "New Delhi", state: "Delhi" },
  { name: "Max Super Speciality Hospital Patparganj Delhi", city: "New Delhi", state: "Delhi" },
  { name: "Max Hospital Gurgaon", city: "Gurugram", state: "Haryana" },
  { name: "Max Hospital Mohali", city: "Mohali", state: "Punjab" },
  { name: "Max Hospital Vaishali", city: "Ghaziabad", state: "Uttar Pradesh" },
  // Medanta
  { name: "Medanta - The Medicity Gurgaon", city: "Gurugram", state: "Haryana" },
  { name: "Medanta Hospital Lucknow", city: "Lucknow", state: "Uttar Pradesh" },
  { name: "Medanta Hospital Patna", city: "Patna", state: "Bihar" },
  { name: "Medanta Hospital Indore", city: "Indore", state: "Madhya Pradesh" },
  // Narayana Health
  { name: "Narayana Health City Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "Narayana Multispeciality Hospital Kolkata", city: "Kolkata", state: "West Bengal" },
  { name: "Narayana Superspeciality Hospital Gurgaon", city: "Gurugram", state: "Haryana" },
  { name: "Narayana Hospital Ahmedabad", city: "Ahmedabad", state: "Gujarat" },
  { name: "Narayana Hospital Jamshedpur", city: "Jamshedpur", state: "Jharkhand" },
  // Manipal Group
  { name: "Manipal Hospital Bengaluru (Old Airport Road)", city: "Bengaluru", state: "Karnataka" },
  { name: "Manipal Hospital Sarjapur Road Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "Manipal Hospital Goa", city: "Panaji", state: "Goa" },
  { name: "Manipal Hospital Dwarka Delhi", city: "New Delhi", state: "Delhi" },
  { name: "Manipal Hospital Jaipur", city: "Jaipur", state: "Rajasthan" },
  // Columbia Asia / Manipal
  { name: "Columbia Asia Hospital Hebbal Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "Columbia Asia Hospital Whitefield Bengaluru", city: "Bengaluru", state: "Karnataka" },
  // Kokilaben / Ambani
  { name: "Kokilaben Dhirubhai Ambani Hospital Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Dhirubhai Ambani Hospital Navi Mumbai", city: "Navi Mumbai", state: "Maharashtra" },
  // Mumbai Private
  { name: "Lilavati Hospital Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Breach Candy Hospital Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Hinduja Hospital Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Jaslok Hospital Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Wockhardt Hospital Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Jupiter Hospital Thane", city: "Thane", state: "Maharashtra" },
  // Delhi NCR
  { name: "Sir Ganga Ram Hospital Delhi", city: "New Delhi", state: "Delhi" },
  { name: "Indraprastha Apollo Hospital Delhi", city: "New Delhi", state: "Delhi" },
  { name: "BLK-Max Super Speciality Hospital Delhi", city: "New Delhi", state: "Delhi" },
  { name: "Moolchand Hospital Delhi", city: "New Delhi", state: "Delhi" },
  { name: "Primus Super Speciality Hospital Delhi", city: "New Delhi", state: "Delhi" },
  { name: "Venkateshwar Hospital Dwarka Delhi", city: "New Delhi", state: "Delhi" },
  // Pune
  { name: "Ruby Hall Clinic Pune", city: "Pune", state: "Maharashtra" },
  { name: "Deenanath Mangeshkar Hospital Pune", city: "Pune", state: "Maharashtra" },
  { name: "Jehangir Hospital Pune", city: "Pune", state: "Maharashtra" },
  // Hyderabad
  { name: "AIG Hospitals Hyderabad", city: "Hyderabad", state: "Telangana" },
  { name: "Continental Hospitals Hyderabad", city: "Hyderabad", state: "Telangana" },
  { name: "KIMS Hospitals Hyderabad", city: "Hyderabad", state: "Telangana" },
  { name: "Yashoda Hospitals Hyderabad", city: "Hyderabad", state: "Telangana" },
  { name: "Care Hospitals Hyderabad", city: "Hyderabad", state: "Telangana" },
  { name: "Sunshine Hospitals Hyderabad", city: "Hyderabad", state: "Telangana" },
  // Bengaluru
  { name: "St John's Medical College Hospital Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "Aster CMI Hospital Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "BGS Gleneagles Global Hospital Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "HCG Hospitals Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "Sparsh Hospital Bengaluru", city: "Bengaluru", state: "Karnataka" },
  // Chennai
  { name: "Sri Ramachandra Medical Centre Chennai", city: "Chennai", state: "Tamil Nadu" },
  { name: "MIOT International Hospital Chennai", city: "Chennai", state: "Tamil Nadu" },
  { name: "Global Health City Chennai", city: "Chennai", state: "Tamil Nadu" },
  { name: "Vijaya Hospital Chennai", city: "Chennai", state: "Tamil Nadu" },
  { name: "Kauvery Hospital Chennai", city: "Chennai", state: "Tamil Nadu" },
  // Kerala
  { name: "Amrita Institute of Medical Sciences Kochi", city: "Kochi", state: "Kerala" },
  { name: "Lakeshore Hospital Kochi", city: "Kochi", state: "Kerala" },
  { name: "Aster MIMS Kozhikode", city: "Kozhikode", state: "Kerala" },
  { name: "Aster Medcity Kochi", city: "Kochi", state: "Kerala" },
  { name: "Believers Church Medical College Hospital", city: "Thiruvalla", state: "Kerala" },
  // Miscellaneous
  { name: "PGIMER RML Hospital", city: "New Delhi", state: "Delhi" },
  { name: "Wockhardt Hospital Nagpur", city: "Nagpur", state: "Maharashtra" },
  { name: "Jupiter Hospital Pune", city: "Pune", state: "Maharashtra" },
  { name: "Holistic Medical Centre", city: "Bengaluru", state: "Karnataka" },
  { name: "Artemis Hospital Gurgaon", city: "Gurugram", state: "Haryana" },
  { name: "Park Hospital Gurgaon", city: "Gurugram", state: "Haryana" },
  { name: "CK Birla Hospital Gurgaon", city: "Gurugram", state: "Haryana" },
  { name: "Sharda Hospital Greater Noida", city: "Greater Noida", state: "Uttar Pradesh" },
  { name: "Era's Lucknow Medical College Hospital", city: "Lucknow", state: "Uttar Pradesh" },
  { name: "Sahara Hospital Lucknow", city: "Lucknow", state: "Uttar Pradesh" },
  { name: "Regency Hospital Kanpur", city: "Kanpur", state: "Uttar Pradesh" },
  { name: "Hinduja Hospital Mahim Mumbai", city: "Mumbai", state: "Maharashtra" },
  { name: "Tata Main Hospital Jamshedpur", city: "Jamshedpur", state: "Jharkhand" },
  { name: "Capital Hospital Bhubaneswar", city: "Bhubaneswar", state: "Odisha" },
  { name: "Hi-Tech Medical College Bhubaneswar", city: "Bhubaneswar", state: "Odisha" },
  { name: "IMS BHU Hospital Varanasi", city: "Varanasi", state: "Uttar Pradesh" },
  { name: "Command Hospital Air Force Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { name: "Army Hospital Research & Referral Delhi", city: "New Delhi", state: "Delhi" },
  { name: "Command Hospital Central Lucknow", city: "Lucknow", state: "Uttar Pradesh" },
  { name: "Military Hospital Pune", city: "Pune", state: "Maharashtra" },
];
