/**
 * seedBooks.ts — run once to insert the comprehensive medical books catalogue.
 * Usage: pnpm --filter @workspace/api-server tsx src/lib/seedBooks.ts
 */
import { db, productsTable } from "@workspace/db";
import { ilike } from "drizzle-orm";

const BOOK_IMG = [
  "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80",
  "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&q=80",
  "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&q=80",
  "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&q=80",
];
const img = (i: number) => BOOK_IMG[i % BOOK_IMG.length];

const books = [
  // ── General / Internal Medicine ─────────────────────────────────
  { name: "Harrison's Principles of Internal Medicine 21st Ed (2-Vol Set)", desc: "The gold-standard internal medicine textbook, updated with the latest clinical guidelines, landmark trials, and comprehensive disease coverage. Essential for every clinician.", price: "8999", orig: "12999", cat: "Books & Study Material", slug: "books", brand: "McGraw-Hill", rating: "4.9", reviews: 1234, tags: ["Harrison", "Internal Medicine", "MBBS", "MD"], featured: true },
  { name: "Davidson's Principles & Practice of Medicine 24th Ed", desc: "The most popular clinical medicine textbook worldwide, beloved by Indian medical students. Clear writing, superb clinical focus, outstanding for MBBS and USMLE.", price: "2999", orig: "3999", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.8", reviews: 2341, tags: ["Davidson", "Medicine", "MBBS"], featured: true },
  { name: "Kumar & Clark's Clinical Medicine 10th Ed", desc: "A cornerstone clinical medicine text with a clear, problem-based approach. Covers the entire spectrum of medical specialties with concise, exam-focused content.", price: "3999", orig: "5499", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.7", reviews: 987, tags: ["Kumar Clark", "Medicine"], featured: false },
  { name: "Oxford Handbook of Clinical Medicine 10th Ed", desc: "The iconic pocket handbook carried by every medical student and junior doctor. Fits in a white coat pocket — covers every clinical scenario you'll encounter.", price: "1999", orig: "2699", cat: "Books & Study Material", slug: "books", brand: "Oxford University Press", rating: "4.9", reviews: 3456, tags: ["Oxford handbook", "clinical"], featured: true },
  { name: "Hutchison's Clinical Methods 24th Ed", desc: "The definitive guide to clinical examination. Covers history-taking, physical examination, and clinical reasoning for all systems. A must-read for MBBS clinical postings.", price: "1499", orig: "1999", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.7", reviews: 1876, tags: ["Hutchison", "clinical methods"], featured: false },
  { name: "Cecil Essentials of Medicine 10th Ed", desc: "Concise, accessible companion to medicine for medical students and residents. Evidence-based, organ-system approach with clinical pearls throughout.", price: "4499", orig: "5999", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.6", reviews: 543, tags: ["Cecil", "medicine"], featured: false },

  // ── Anatomy ─────────────────────────────────────────────────────
  { name: "Gray's Anatomy 42nd Edition", desc: "The definitive human anatomy reference for 160 years. Stunning anatomical illustrations, clinical correlations, and radiological images. Essential for every medical student.", price: "7499", orig: "9999", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.9", reviews: 2109, tags: ["Gray's Anatomy", "anatomy"], featured: false },
  { name: "BD Chaurasia Human Anatomy Vol 1-3 (Indian Ed)", desc: "The most popular anatomy textbook among Indian MBBS students. Comprehensive coverage of upper limb, lower limb, thorax, abdomen, head & neck in 3 volumes with detailed line diagrams.", price: "1899", orig: "2499", cat: "Books & Study Material", slug: "books", brand: "CBS Publishers", rating: "4.8", reviews: 4532, tags: ["BD Chaurasia", "anatomy", "MBBS India"], featured: true },
  { name: "Snell's Clinical Anatomy by Regions 10th Ed", desc: "Region-based anatomy with exceptional clinical correlations and case studies. Ideal for understanding anatomy in a clinical context. Widely used for USMLE Step 1.", price: "5499", orig: "7499", cat: "Books & Study Material", slug: "books", brand: "Wolters Kluwer", rating: "4.8", reviews: 876, tags: ["Snell", "anatomy", "clinical"], featured: false },
  { name: "Last's Anatomy 9th Edition", desc: "A classic regional anatomy textbook with an emphasis on surgical anatomy. Precise descriptions of anatomical relationships essential for surgical practice.", price: "3999", orig: "5499", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.7", reviews: 654, tags: ["Last's anatomy", "anatomy"], featured: false },
  { name: "Netter's Atlas of Human Anatomy 8th Ed", desc: "The world's best-selling anatomy atlas with Frank Netter's unparalleled medical illustrations. 640 colour plates, each with clinical notes. A visual masterpiece.", price: "6999", orig: "9499", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.9", reviews: 1567, tags: ["Netter", "anatomy atlas"], featured: false },
  { name: "KD Tripathi Review of Anatomy (PGMEE Series)", desc: "High-yield NEET-PG review of anatomy with MCQs, previous year questions, and detailed explanations. Ideal for PG entrance preparation.", price: "799", orig: "999", cat: "Books & Study Material", slug: "books", brand: "Jaypee Brothers", rating: "4.6", reviews: 2100, tags: ["anatomy review", "NEET-PG", "PGMEE"], featured: false },
  { name: "Inderbir Singh's Human Embryology 11th Ed", desc: "The standard embryology text for Indian medical students. Clear descriptions of embryological development with clinical significance of congenital anomalies.", price: "799", orig: "1099", cat: "Books & Study Material", slug: "books", brand: "CBS Publishers", rating: "4.7", reviews: 1876, tags: ["embryology", "Inderbir Singh"], featured: false },

  // ── Physiology ──────────────────────────────────────────────────
  { name: "Guyton & Hall Medical Physiology 14th Ed", desc: "The world's most trusted physiology textbook. Clear explanations of complex physiological processes with clinical correlations. Ideal for MBBS first year.", price: "4999", orig: "6499", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.9", reviews: 3210, tags: ["Guyton Hall", "physiology", "MBBS"], featured: false },
  { name: "AK Jain Textbook of Physiology 8th Ed (2-Vol)", desc: "The most widely used physiology textbook in India. Comprehensive, exam-oriented approach with MCQs. Covers all topics as per MCI/NMC curriculum.", price: "1299", orig: "1599", cat: "Books & Study Material", slug: "books", brand: "Avichal Publishing", rating: "4.7", reviews: 3987, tags: ["AK Jain", "physiology", "India"], featured: true },
  { name: "Ganong's Review of Medical Physiology 26th Ed", desc: "The authoritative physiology review covering endocrine, cardiovascular, renal, and neurophysiology. Best for USMLE, PGMEE, and in-depth understanding.", price: "4299", orig: "5799", cat: "Books & Study Material", slug: "books", brand: "McGraw-Hill", rating: "4.8", reviews: 1432, tags: ["Ganong", "physiology"], featured: false },
  { name: "Linda Costanzo Physiology 7th Ed", desc: "Concise, clear physiology text with an emphasis on mechanisms and clinical relevance. Popular for boards preparation and USMLE Step 1 review.", price: "3499", orig: "4799", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.7", reviews: 876, tags: ["Costanzo", "physiology", "USMLE"], featured: false },
  { name: "BRS Physiology 8th Ed (Board Review Series)", desc: "High-yield physiology review in outline format. Concise, packed with clinical correlations, questions, and exam tips — ideal USMLE and NEET-PG preparation.", price: "2999", orig: "3999", cat: "Books & Study Material", slug: "books", brand: "Wolters Kluwer", rating: "4.7", reviews: 765, tags: ["BRS physiology", "USMLE", "board review"], featured: false },

  // ── Biochemistry ─────────────────────────────────────────────────
  { name: "Harper's Illustrated Biochemistry 32nd Ed", desc: "The most comprehensive medical biochemistry textbook. Covers molecular biology, metabolism, clinical correlations, and laboratory diagnostics with stunning illustrations.", price: "5499", orig: "7299", cat: "Books & Study Material", slug: "books", brand: "McGraw-Hill", rating: "4.8", reviews: 1098, tags: ["Harper's", "biochemistry"], featured: false },
  { name: "DM Vasudevan Textbook of Biochemistry 9th Ed", desc: "The most popular biochemistry textbook for Indian MBBS students. Comprehensive, exam-focused content aligned with NMC curriculum.", price: "999", orig: "1299", cat: "Books & Study Material", slug: "books", brand: "Jaypee Brothers", rating: "4.7", reviews: 3654, tags: ["Vasudevan", "biochemistry", "MBBS India"], featured: true },
  { name: "Lippincott's Illustrated Reviews: Biochemistry 8th Ed", desc: "High-yield biochemistry review with outstanding colour illustrations. Each chapter ends with boards-style questions. Essential for USMLE Step 1 preparation.", price: "3999", orig: "5499", cat: "Books & Study Material", slug: "books", brand: "Wolters Kluwer", rating: "4.8", reviews: 1234, tags: ["Lippincott", "biochemistry", "USMLE"], featured: false },
  { name: "Satyanarayan Biochemistry 5th Ed", desc: "Comprehensive Indian biochemistry textbook with clinical correlations and important exam questions. Widely used in Indian medical colleges.", price: "899", orig: "1199", cat: "Books & Study Material", slug: "books", brand: "Books and Allied", rating: "4.6", reviews: 2876, tags: ["Satyanarayan", "biochemistry", "India"], featured: false },

  // ── Pathology ────────────────────────────────────────────────────
  { name: "Robbins & Cotran Pathologic Basis of Disease 10th Ed", desc: "The gold standard pathology textbook. Comprehensive coverage of mechanisms of disease with outstanding gross and microscopic pathology images.", price: "7499", orig: "9999", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.9", reviews: 2345, tags: ["Robbins", "pathology"], featured: false },
  { name: "Robbins Basic Pathology 10th Ed", desc: "The concise Robbins for MBBS students. Covers all major pathological processes without the overwhelming detail of the full text. Perfect for exam preparation.", price: "4499", orig: "5999", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.8", reviews: 1987, tags: ["Robbins Basic", "pathology", "MBBS"], featured: true },
  { name: "Harsh Mohan Textbook of Pathology 8th Ed", desc: "The most popular pathology text among Indian medical students. Exam-oriented, comprehensive, with colour microphotographs. Trusted by generations of doctors.", price: "1099", orig: "1499", cat: "Books & Study Material", slug: "books", brand: "Jaypee Brothers", rating: "4.8", reviews: 4321, tags: ["Harsh Mohan", "pathology", "India"], featured: true },
  { name: "Devita Hellman Rosenberg's Pathology Review", desc: "A high-yield pathology review book with 600 clinical vignette MCQs aligned with USMLE Step 1. Detailed explanations and learning objectives.", price: "2999", orig: "3999", cat: "Books & Study Material", slug: "books", brand: "McGraw-Hill", rating: "4.6", reviews: 543, tags: ["pathology review", "USMLE"], featured: false },
  { name: "Goljan Rapid Review Pathology 5th Ed", desc: "Edward Goljan's legendary rapid review — the highest-yield pathology review available. Concise tables, clinical correlations and USMLE-style questions.", price: "3499", orig: "4799", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.9", reviews: 1654, tags: ["Goljan", "pathology", "rapid review"], featured: false },
  { name: "Muir's Textbook of Pathology 15th Ed", desc: "A systematic pathology textbook with an emphasis on mechanisms of disease and clinical significance. Well-illustrated with gross and histological images.", price: "5499", orig: "7499", cat: "Books & Study Material", slug: "books", brand: "CRC Press", rating: "4.7", reviews: 432, tags: ["Muir", "pathology"], featured: false },

  // ── Pharmacology ─────────────────────────────────────────────────
  { name: "KD Tripathi Essentials of Medical Pharmacology 9th Ed", desc: "The most widely used pharmacology textbook in India. Clear writing, excellent drug classifications, and comprehensive coverage of all drugs with mechanisms and clinical uses.", price: "999", orig: "1299", cat: "Books & Study Material", slug: "books", brand: "Jaypee Brothers", rating: "4.9", reviews: 5678, tags: ["Tripathi", "pharmacology", "India"], featured: true },
  { name: "Goodman & Gilman's Pharmacological Basis of Therapeutics 14th Ed", desc: "The comprehensive pharmacology bible. Covers receptor pharmacology, all drug classes, and toxicology in unparalleled depth. Essential for MD pharmacology.", price: "9499", orig: "12999", cat: "Books & Study Material", slug: "books", brand: "McGraw-Hill", rating: "4.9", reviews: 876, tags: ["Goodman Gilman", "pharmacology"], featured: false },
  { name: "Lippincott's Illustrated Reviews: Pharmacology 8th Ed", desc: "High-yield pharmacology review with clear mechanisms, charts, and boards-style questions. Outstanding colour illustrations of drug mechanisms.", price: "3499", orig: "4799", cat: "Books & Study Material", slug: "books", brand: "Wolters Kluwer", rating: "4.8", reviews: 1234, tags: ["Lippincott", "pharmacology", "USMLE"], featured: false },
  { name: "Katzung Basic & Clinical Pharmacology 16th Ed", desc: "A comprehensive pharmacology text bridging basic science and clinical medicine. Preferred by US medical schools for its balance of depth and readability.", price: "5999", orig: "7999", cat: "Books & Study Material", slug: "books", brand: "McGraw-Hill", rating: "4.8", reviews: 765, tags: ["Katzung", "pharmacology"], featured: false },
  { name: "Satoskar Pharmacology & Pharmacotherapeutics 25th Ed", desc: "The classic Indian pharmacology reference. Updated with new drugs, NMC guidelines, and Indian drug formulations. Preferred for PGMEE preparation.", price: "1199", orig: "1599", cat: "Books & Study Material", slug: "books", brand: "Popular Prakashan", rating: "4.7", reviews: 2109, tags: ["Satoskar", "pharmacology", "India"], featured: false },

  // ── Microbiology ─────────────────────────────────────────────────
  { name: "Ananthanarayan & Paniker Textbook of Microbiology 11th Ed", desc: "The most popular microbiology textbook in India. Systematic coverage of bacteriology, virology, mycology, and parasitology with an emphasis on Indian pathogens.", price: "799", orig: "1099", cat: "Books & Study Material", slug: "books", brand: "Universities Press", rating: "4.8", reviews: 4321, tags: ["Ananthanarayan", "microbiology", "India"], featured: true },
  { name: "Jawetz Melnick & Adelberg's Medical Microbiology 28th Ed", desc: "The comprehensive medical microbiology reference for USMLE and postgraduate preparation. Covers microbial genetics, pathogenesis, immunity, and clinical syndromes.", price: "4999", orig: "6799", cat: "Books & Study Material", slug: "books", brand: "McGraw-Hill", rating: "4.8", reviews: 876, tags: ["Jawetz", "microbiology", "USMLE"], featured: false },
  { name: "Greenwood Medical Microbiology 19th Ed", desc: "Excellent integrated microbiology and infectious disease textbook. Clinical case studies, public health aspects, and antimicrobial pharmacology fully updated.", price: "4499", orig: "5999", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.7", reviews: 543, tags: ["Greenwood", "microbiology"], featured: false },
  { name: "Mackie & McCartney Practical Medical Microbiology 14th Ed", desc: "The standard reference for clinical microbiology laboratory practice. Comprehensive coverage of diagnostic bacteriology, virology, and mycology techniques.", price: "5999", orig: "7999", cat: "Books & Study Material", slug: "books", brand: "Elsevier", rating: "4.8", reviews: 234, tags: ["Mackie McCartney", "microbiology", "lab"], featured: false },

  // ── Surgery ──────────────────────────────────────────────────────
  { name: "Bailey & Love's Short Practice of Surgery 28th Ed", desc: "The classic surgical textbook trusted by generations worldwide. Comprehensive coverage of general surgery, subspecialties, critical care, and operative techniques.", price: "4999", orig: "6999", cat: "Surgery", slug: "surgical", brand: "CRC Press", rating: "4.9", reviews: 2109, tags: ["Bailey Love", "surgery"], featured: true },
  { name: "SRB's Manual of Surgery 6th Ed", desc: "The most popular surgery textbook for Indian MBBS students and surgical residents. Exam-focused, comprehensive, with operative notes and clinical photographs.", price: "1499", orig: "1999", cat: "Surgery", slug: "surgical", brand: "Jaypee Brothers", rating: "4.8", reviews: 3456, tags: ["SRB", "surgery", "India"], featured: true },
  { name: "Sabiston Textbook of Surgery 21st Ed", desc: "The definitive American surgery text. Covers every surgical specialty with evidence-based guidelines, operative techniques, and outcomes data.", price: "14999", orig: "19999", cat: "Surgery", slug: "surgical", brand: "Elsevier", rating: "4.9", reviews: 765, tags: ["Sabiston", "surgery"], featured: false },
  { name: "Schwartz's Principles of Surgery 11th Ed", desc: "A comprehensive surgical text with an emphasis on clinical decision-making and evidence-based practice. Updated with minimally invasive and robotic surgical techniques.", price: "12999", orig: "17999", cat: "Surgery", slug: "surgical", brand: "McGraw-Hill", rating: "4.8", reviews: 654, tags: ["Schwartz", "surgery"], featured: false },
  { name: "Browse's Introduction to the Symptoms and Signs of Surgical Disease 5th Ed", desc: "The guide to surgical diagnosis — covers symptoms, signs, and clinical reasoning for all surgical conditions. Builds diagnostic thinking skills essential for surgery postings.", price: "3499", orig: "4799", cat: "Surgery", slug: "surgical", brand: "CRC Press", rating: "4.7", reviews: 876, tags: ["Browse", "surgical diagnosis"], featured: false },
  { name: "Hamilton Bailey's Physical Signs in Clinical Surgery 19th Ed", desc: "The masterpiece of clinical examination in surgery. Iconic clinical photographs and case studies. Invaluable for MS surgery vivas and clinical rounds.", price: "2499", orig: "3499", cat: "Surgery", slug: "surgical", brand: "CRC Press", rating: "4.8", reviews: 1234, tags: ["Hamilton Bailey", "surgery"], featured: false },
  { name: "Das & Das Surgery of the Abdomen & Pelvis", desc: "Detailed operative surgery manual for abdominal procedures. Indian context, step-by-step techniques for common operations with colour operative photographs.", price: "2999", orig: "3999", cat: "Surgery", slug: "surgical", brand: "S Das Publishers", rating: "4.7", reviews: 987, tags: ["Das surgery", "abdominal surgery", "India"], featured: false },

  // ── Cardiology ───────────────────────────────────────────────────
  { name: "Braunwald's Heart Disease 12th Ed (2-Vol Set)", desc: "The definitive cardiology reference. Covers pathophysiology, diagnosis, and management of all cardiac diseases with evidence-based practice guidelines.", price: "9499", orig: "12999", cat: "Cardiology", slug: "cardiac-care", brand: "Elsevier", rating: "4.9", reviews: 876, tags: ["Braunwald", "cardiology"], featured: false },
  { name: "Hurst's The Heart 14th Ed", desc: "Comprehensive cardiology textbook with state-of-the-art imaging, interventional cardiology, and cardiovascular surgery. A key reference for cardiologists.", price: "8999", orig: "11999", cat: "Cardiology", slug: "cardiac-care", brand: "McGraw-Hill", rating: "4.8", reviews: 432, tags: ["Hurst", "cardiology"], featured: false },
  { name: "Chung's Cardiac Arrhythmias: Self-Assessment 3rd Ed", desc: "ECG tracing workbook with 150 arrhythmia cases. Self-assessment format ideal for cardiology fellows and practicing cardiologists reviewing electrophysiology.", price: "3499", orig: "4499", cat: "Cardiology", slug: "cardiac-care", brand: "Wolters Kluwer", rating: "4.7", reviews: 321, tags: ["arrhythmia", "ECG", "cardiology"], featured: false },
  { name: "Chou's Electrocardiography in Clinical Practice 6th Ed", desc: "The most detailed ECG interpretation text available. 900+ ECG tracings with thorough analysis covering all arrhythmias, conduction defects, and ischaemia patterns.", price: "5999", orig: "7999", cat: "Cardiology", slug: "cardiac-care", brand: "Elsevier", rating: "4.9", reviews: 543, tags: ["ECG", "electrocardiography"], featured: false },
  { name: "Topol Textbook of Interventional Cardiology 8th Ed", desc: "The authoritative guide to percutaneous coronary intervention, structural heart disease, and peripheral vascular intervention.", price: "11999", orig: "15999", cat: "Cardiology", slug: "cardiac-care", brand: "Elsevier", rating: "4.8", reviews: 234, tags: ["interventional cardiology", "PCI"], featured: false },

  // ── Neurology ────────────────────────────────────────────────────
  { name: "Adams & Victor Principles of Neurology 11th Ed", desc: "The most comprehensive neurology textbook. Systematic clinical neurology with an exceptional chapter on neurological examination and localisation of lesions.", price: "7499", orig: "9999", cat: "Neurology", slug: "neurology", brand: "McGraw-Hill", rating: "4.9", reviews: 654, tags: ["Adams Victor", "neurology"], featured: false },
  { name: "Hauser's Harrison's Neurology in Clinical Medicine 4th Ed", desc: "The neurology section of Harrison's, standalone. Covers stroke, epilepsy, dementia, MS, and movement disorders with latest evidence-based management.", price: "4999", orig: "6799", cat: "Neurology", slug: "neurology", brand: "McGraw-Hill", rating: "4.8", reviews: 432, tags: ["Harrison neurology", "neurology"], featured: false },
  { name: "Rohkamm Neurology Colour Atlas 4th Ed", desc: "Superbly illustrated neurology atlas. All major neurological diseases presented with anatomical diagrams, clinical photographs, and MRI/CT images.", price: "3999", orig: "5499", cat: "Neurology", slug: "neurology", brand: "Thieme", rating: "4.8", reviews: 312, tags: ["neurology atlas", "neurology"], featured: false },
  { name: "NINDS Stroke Scale & Neurological Assessment Handbook", desc: "Practical pocket guide to NIH Stroke Scale scoring, GCS, NIHSS, and neurological examination with laminated quick-reference cards.", price: "699", orig: "999", cat: "Neurology", slug: "neurology", brand: "Jaypee Brothers", rating: "4.6", reviews: 876, tags: ["NIHSS", "stroke", "neurology"], featured: false },

  // ── Gastroenterology ─────────────────────────────────────────────
  { name: "Sleisenger & Fordtran's GI & Liver Disease 11th Ed (2-Vol)", desc: "The authoritative gastroenterology reference. Comprehensive coverage of all GI disorders, IBD, NAFLD, hepatology, and GI cancers with updated treatment guidelines.", price: "11999", orig: "15999", cat: "Gastroenterology", slug: "gastroenterology", brand: "Elsevier", rating: "4.9", reviews: 432, tags: ["Sleisenger Fordtran", "gastroenterology"], featured: false },
  { name: "Yamada's Textbook of Gastroenterology 6th Ed (2-Vol)", desc: "Comprehensive gastroenterology and hepatology reference. Known for evidence-based approach, imaging, and integrating basic science with clinical practice.", price: "13999", orig: "18999", cat: "Gastroenterology", slug: "gastroenterology", brand: "Wiley-Blackwell", rating: "4.8", reviews: 312, tags: ["Yamada", "gastroenterology"], featured: false },
  { name: "Clinical Gastroenterology - Makharia & Ahuja (Indian Ed)", desc: "Indian gastroenterology and hepatology textbook covering tropical infections, NAFLD, IBD, and liver disease with Indian epidemiological data.", price: "2999", orig: "3999", cat: "Gastroenterology", slug: "gastroenterology", brand: "Jaypee Brothers", rating: "4.7", reviews: 543, tags: ["gastroenterology", "India"], featured: false },

  // ── Nephrology ───────────────────────────────────────────────────
  { name: "Brenner & Rector's The Kidney 11th Ed (2-Vol)", desc: "The world's foremost nephrology reference. Covers all aspects of kidney disease from basic science to clinical management, dialysis, and transplantation.", price: "13999", orig: "18999", cat: "Nephrology", slug: "nephrology", brand: "Elsevier", rating: "4.9", reviews: 234, tags: ["Brenner Rector", "nephrology"], featured: false },
  { name: "Comprehensive Clinical Nephrology 6th Ed", desc: "Practical, clinically oriented nephrology textbook. Excellent coverage of CKD, AKI, glomerulonephritis, electrolyte disorders, and renal replacement therapy.", price: "8999", orig: "11999", cat: "Nephrology", slug: "nephrology", brand: "Elsevier", rating: "4.8", reviews: 312, tags: ["nephrology", "CKD"], featured: false },
  { name: "KDIGO Clinical Practice Guidelines — CKD & AKI (2024 Edition)", desc: "The latest KDIGO guidelines for CKD and AKI diagnosis, staging, and management. Essential reference for nephrologists and intensivists.", price: "1499", orig: "1999", cat: "Nephrology", slug: "nephrology", brand: "Kidney International Supplements", rating: "4.9", reviews: 456, tags: ["KDIGO", "CKD", "AKI", "nephrology"], featured: false },

  // ── Pulmonology ──────────────────────────────────────────────────
  { name: "Murray & Nadel's Textbook of Respiratory Medicine 7th Ed", desc: "The definitive pulmonology reference. Covers ARDS, ILD, COPD, pulmonary hypertension, lung cancer, and thoracic surgery with updated evidence-based guidelines.", price: "12999", orig: "16999", cat: "Pulmonology", slug: "pulmonology", brand: "Elsevier", rating: "4.9", reviews: 321, tags: ["Murray Nadel", "pulmonology"], featured: false },
  { name: "GOLD COPD Pocket Guide 2024", desc: "The latest GOLD initiative pocket guide for COPD diagnosis, classification, management, and prevention. Essential quick-reference for respiratory physicians.", price: "599", orig: "799", cat: "Pulmonology", slug: "pulmonology", brand: "GOLD Initiative", rating: "4.8", reviews: 1234, tags: ["COPD", "GOLD", "pulmonology"], featured: false },
  { name: "GINA Asthma Management Pocket Guide 2024", desc: "Latest GINA guidelines for asthma management, step therapy, and biologics. Includes asthma control test and exacerbation management protocols.", price: "599", orig: "799", cat: "Pulmonology", slug: "pulmonology", brand: "GINA", rating: "4.8", reviews: 1087, tags: ["asthma", "GINA", "pulmonology"], featured: false },
  { name: "Principles of Pulmonary Medicine 7th Ed", desc: "Accessible pulmonology text for students and generalists. Covers the pathophysiology, diagnosis, and treatment of all major respiratory diseases.", price: "3999", orig: "5499", cat: "Pulmonology", slug: "pulmonology", brand: "Elsevier", rating: "4.7", reviews: 432, tags: ["pulmonology", "respiratory medicine"], featured: false },

  // ── Ophthalmology ────────────────────────────────────────────────
  { name: "Kanski's Clinical Ophthalmology 9th Ed", desc: "The most comprehensive clinical ophthalmology atlas. Thousands of high-quality fundus photographs, slit-lamp images, and clinical photographs across all subspecialties.", price: "8999", orig: "11999", cat: "Ophthalmology", slug: "ophthalmology", brand: "Elsevier", rating: "4.9", reviews: 654, tags: ["Kanski", "ophthalmology"], featured: false },
  { name: "AK Khurana Comprehensive Ophthalmology 7th Ed", desc: "The most popular ophthalmology textbook for Indian MBBS and DO students. Complete coverage with colour photographs and exam-focused MCQs.", price: "1299", orig: "1699", cat: "Ophthalmology", slug: "ophthalmology", brand: "CBS Publishers", rating: "4.8", reviews: 2876, tags: ["Khurana", "ophthalmology", "India"], featured: true },
  { name: "Vaughan & Asbury's General Ophthalmology 19th Ed", desc: "Widely used international ophthalmology textbook. Systematic coverage of all eye diseases with clinical photographs and updated management algorithms.", price: "3999", orig: "5499", cat: "Ophthalmology", slug: "ophthalmology", brand: "McGraw-Hill", rating: "4.7", reviews: 543, tags: ["Vaughan Asbury", "ophthalmology"], featured: false },
  { name: "Basic and Clinical Science Course (BCSC) — AAO Subspecialty Set", desc: "The American Academy of Ophthalmology's comprehensive 13-volume set covering all ophthalmology subspecialties. The gold standard for ophthalmology board preparation.", price: "24999", orig: "31999", cat: "Ophthalmology", slug: "ophthalmology", brand: "AAO", rating: "4.9", reviews: 123, tags: ["AAO", "ophthalmology", "BCSC"], featured: false },

  // ── Paediatrics ──────────────────────────────────────────────────
  { name: "Nelson Textbook of Pediatrics 21st Ed (2-Vol)", desc: "The gold standard paediatrics reference. Comprehensive coverage of newborn medicine, developmental paediatrics, and evidence-based clinical care.", price: "9999", orig: "12999", cat: "Paediatrics", slug: "paediatric", brand: "Elsevier", rating: "4.9", reviews: 1234, tags: ["Nelson", "paediatrics"], featured: false },
  { name: "OP Ghai Essential Pediatrics 9th Ed", desc: "The most trusted paediatrics textbook in India. Comprehensive, exam-oriented with IMNCI protocols, Indian immunisation schedule, and NMC-aligned content.", price: "1299", orig: "1699", cat: "Paediatrics", slug: "paediatric", brand: "CBS Publishers", rating: "4.8", reviews: 3210, tags: ["OP Ghai", "paediatrics", "India"], featured: true },
  { name: "Forfar & Arneil's Textbook of Paediatrics 7th Ed", desc: "Comprehensive paediatrics text with excellent sections on child development, nutrition, and evidence-based management of all paediatric conditions.", price: "7999", orig: "10999", cat: "Paediatrics", slug: "paediatric", brand: "Elsevier", rating: "4.7", reviews: 432, tags: ["Forfar Arneil", "paediatrics"], featured: false },
  { name: "IAP Textbook of Paediatrics 6th Ed", desc: "The Indian Academy of Pediatrics textbook aligned with Indian epidemiology and practice. Covers tropical diseases, malnutrition, and indigenous treatment protocols.", price: "1999", orig: "2699", cat: "Paediatrics", slug: "paediatric", brand: "Jaypee Brothers", rating: "4.8", reviews: 1654, tags: ["IAP", "paediatrics", "India"], featured: false },

  // ── Dermatology ──────────────────────────────────────────────────
  { name: "Fitzpatrick's Dermatology 9th Ed (2-Vol Set)", desc: "The definitive dermatology reference with outstanding clinical photography. Covers all skin diseases, therapies, and procedures with landmark research updates.", price: "16999", orig: "22999", cat: "Dermatology", slug: "dermatology", brand: "McGraw-Hill", rating: "4.9", reviews: 543, tags: ["Fitzpatrick", "dermatology"], featured: false },
  { name: "VN Sehgal Dermatology for Skin of Colour (Indian Ed)", desc: "A comprehensive dermatology text focusing on South Asian skin. Covers tropical dermatoses, pigmentary disorders, and skin conditions common in Indian patients.", price: "3499", orig: "4699", cat: "Dermatology", slug: "dermatology", brand: "Jaypee Brothers", rating: "4.7", reviews: 876, tags: ["Sehgal", "dermatology", "India"], featured: false },
  { name: "Rook's Textbook of Dermatology 9th Ed (4-Vol Set)", desc: "The most authoritative dermatology reference. Unparalleled depth of coverage with thousands of clinical images, histology, and evidence-based treatment.", price: "29999", orig: "39999", cat: "Dermatology", slug: "dermatology", brand: "Wiley-Blackwell", rating: "4.9", reviews: 234, tags: ["Rook", "dermatology"], featured: false },

  // ── ENT ──────────────────────────────────────────────────────────
  { name: "Cummings Otolaryngology Head & Neck Surgery 7th Ed (3-Vol)", desc: "The authoritative ENT reference covering rhinology, otology, head & neck oncology, and laryngology with the latest surgical techniques.", price: "14999", orig: "19999", cat: "ENT", slug: "ent", brand: "Elsevier", rating: "4.9", reviews: 321, tags: ["Cummings", "ENT"], featured: false },
  { name: "PL Dhingra Diseases of Ear, Nose & Throat 7th Ed", desc: "The most popular ENT textbook in India. Exam-focused, comprehensive coverage with colour photographs. Trusted by Indian medical students for decades.", price: "999", orig: "1299", cat: "ENT", slug: "ent", brand: "Elsevier", rating: "4.8", reviews: 3456, tags: ["Dhingra", "ENT", "India"], featured: true },
  { name: "Scott-Brown's Otorhinolaryngology 8th Ed (3-Vol)", desc: "The European standard ENT reference. Comprehensive coverage of all ENT subspecialties with evidence-based management and operative techniques.", price: "18999", orig: "24999", cat: "ENT", slug: "ent", brand: "CRC Press", rating: "4.8", reviews: 234, tags: ["Scott-Brown", "ENT"], featured: false },
  { name: "DeWeese & Saunders Textbook of Otolaryngology 8th Ed", desc: "Classical ENT textbook with systematic approach to ear diseases, nasal disorders, throat conditions, and head & neck surgery.", price: "4999", orig: "6799", cat: "ENT", slug: "ent", brand: "Mosby", rating: "4.7", reviews: 345, tags: ["DeWeese Saunders", "ENT"], featured: false },

  // ── Gynaecology & Obs ────────────────────────────────────────────
  { name: "Williams Obstetrics 26th Ed", desc: "The most comprehensive obstetrics reference. Evidence-based guidance on normal and high-risk pregnancy, labour, postpartum care, and obstetric emergencies.", price: "7999", orig: "10999", cat: "Gynaecology & Obs", slug: "gynaecology", brand: "McGraw-Hill", rating: "4.9", reviews: 876, tags: ["Williams Obstetrics", "obstetrics"], featured: false },
  { name: "DC Dutta Textbook of Obstetrics 10th Ed", desc: "The most popular obstetrics textbook in India. Covers normal and abnormal pregnancy with Indian context, FOGSI guidelines, and exam-focused MCQs.", price: "1199", orig: "1599", cat: "Gynaecology & Obs", slug: "gynaecology", brand: "Jaypee Brothers", rating: "4.8", reviews: 3210, tags: ["DC Dutta", "obstetrics", "India"], featured: true },
  { name: "DC Dutta Textbook of Gynaecology 8th Ed", desc: "The companion gynaecology textbook. Comprehensive coverage of gynaecological disorders, infertility, oncology, and minimally invasive procedures.", price: "1099", orig: "1499", cat: "Gynaecology & Obs", slug: "gynaecology", brand: "Jaypee Brothers", rating: "4.8", reviews: 2765, tags: ["DC Dutta", "gynaecology", "India"], featured: true },
  { name: "Novak's Gynecology 15th Ed", desc: "The definitive gynaecology text. Evidence-based management of endometriosis, PCOS, uterine fibroids, and gynaecological cancers with surgical techniques.", price: "9499", orig: "12999", cat: "Gynaecology & Obs", slug: "gynaecology", brand: "Wolters Kluwer", rating: "4.8", reviews: 543, tags: ["Novak", "gynaecology"], featured: false },
  { name: "TeLinde's Operative Gynecology 12th Ed", desc: "The gold standard gynaecological surgery reference. Detailed operative techniques for all major gynaecological procedures with surgical photographs.", price: "11999", orig: "15999", cat: "Gynaecology & Obs", slug: "gynaecology", brand: "Wolters Kluwer", rating: "4.9", reviews: 312, tags: ["TeLinde", "gynaecology surgery"], featured: false },

  // ── Endocrinology ────────────────────────────────────────────────
  { name: "Williams Textbook of Endocrinology 14th Ed", desc: "The definitive endocrinology reference. Covers pituitary, thyroid, adrenal, reproductive endocrinology, diabetes, and metabolic bone disease.", price: "9499", orig: "12999", cat: "Endocrinology", slug: "endocrinology", brand: "Elsevier", rating: "4.9", reviews: 432, tags: ["Williams Endocrinology", "endocrinology"], featured: false },
  { name: "API Textbook of Medicine — Endocrinology Section 11th Ed", desc: "The Association of Physicians of India's comprehensive medicine text with updated endocrinology section. Indian context with local drug availability.", price: "3499", orig: "4699", cat: "Endocrinology", slug: "endocrinology", brand: "Jaypee Brothers", rating: "4.7", reviews: 876, tags: ["API", "endocrinology", "India"], featured: false },
  { name: "RSSDI Clinical Practice Recommendations 2022-23", desc: "Research Society for the Study of Diabetes in India's annual clinical practice recommendations for diabetes management in the Indian population.", price: "1299", orig: "1799", cat: "Endocrinology", slug: "endocrinology", brand: "RSSDI", rating: "4.8", reviews: 765, tags: ["RSSDI", "diabetes", "India"], featured: false },

  // ── Emergency Medicine ────────────────────────────────────────────
  { name: "Tintinalli's Emergency Medicine 9th Ed (2-Vol)", desc: "The most comprehensive emergency medicine textbook. Covers resuscitation, toxicology, trauma, paediatric emergencies, and disaster medicine.", price: "9999", orig: "13999", cat: "Emergency Medicine", slug: "emergency", brand: "McGraw-Hill", rating: "4.9", reviews: 876, tags: ["Tintinalli", "emergency medicine"], featured: false },
  { name: "Roberts & Hedges' Clinical Procedures in Emergency Medicine 7th Ed", desc: "The essential procedural guide for emergency medicine. Step-by-step instructions with photographs for every ED procedure from intubation to thoracocentesis.", price: "7999", orig: "10999", cat: "Emergency Medicine", slug: "emergency", brand: "Elsevier", rating: "4.8", reviews: 543, tags: ["Roberts Hedges", "emergency procedures"], featured: false },
  { name: "ATLS Advanced Trauma Life Support 10th Ed (ACS)", desc: "The American College of Surgeons' ATLS course manual. The global standard for initial trauma assessment and resuscitation. Essential for all doctors.", price: "4499", orig: "5999", cat: "Emergency Medicine", slug: "emergency", brand: "ACS", rating: "4.9", reviews: 2109, tags: ["ATLS", "trauma", "emergency"], featured: true },
  { name: "ACLS Study Guide 6th Ed (AHA)", desc: "The American Heart Association's ACLS provider manual. Advanced cardiac life support algorithms, pharmacology, and team dynamics.", price: "2999", orig: "3999", cat: "Emergency Medicine", slug: "emergency", brand: "AHA / Elsevier", rating: "4.9", reviews: 1876, tags: ["ACLS", "cardiac arrest", "resuscitation"], featured: false },

  // ── Radiology ────────────────────────────────────────────────────
  { name: "Grainger & Allison's Diagnostic Radiology 7th Ed (2-Vol)", desc: "The definitive radiology reference. Comprehensive coverage of all imaging modalities — X-ray, CT, MRI, ultrasound, and nuclear medicine with superb images.", price: "18999", orig: "24999", cat: "Radiology", slug: "radiology", brand: "Elsevier", rating: "4.9", reviews: 312, tags: ["Grainger Allison", "radiology"], featured: false },
  { name: "Brant & Helms Fundamentals of Diagnostic Radiology 5th Ed (4-Vol)", desc: "The most comprehensive radiology textbook for residents and radiologists. Each volume covers a subspecialty with thousands of high-quality images.", price: "14999", orig: "19999", cat: "Radiology", slug: "radiology", brand: "Wolters Kluwer", rating: "4.8", reviews: 234, tags: ["Brant Helms", "radiology"], featured: false },
  { name: "Sutton's Textbook of Radiology and Imaging 7th Ed (2-Vol)", desc: "Comprehensive clinical radiology textbook with emphasis on radiological diagnosis of common and rare diseases. Well-illustrated with plain radiographs.", price: "7999", orig: "10999", cat: "Radiology", slug: "radiology", brand: "Elsevier", rating: "4.7", reviews: 345, tags: ["Sutton", "radiology"], featured: false },
  { name: "Clinical Ultrasonography - Ahuja & Evans 3rd Ed", desc: "Practical ultrasound textbook covering abdominal, pelvic, obstetric, and vascular applications. Excellent for residents and general physicians learning point-of-care ultrasound.", price: "4999", orig: "6799", cat: "Radiology", slug: "radiology", brand: "Elsevier", rating: "4.7", reviews: 432, tags: ["ultrasound", "radiology", "POCUS"], featured: false },

  // ── Oncology ─────────────────────────────────────────────────────
  { name: "DeVita, Hellman & Rosenberg's Cancer 12th Ed (2-Vol)", desc: "The foremost oncology textbook. Covers cancer biology, carcinogenesis, radiation oncology, surgical oncology, and all tumour types with latest clinical trial data.", price: "14999", orig: "19999", cat: "Oncology", slug: "oncology", brand: "Wolters Kluwer", rating: "4.9", reviews: 312, tags: ["DeVita", "oncology"], featured: false },
  { name: "NCCN Clinical Practice Guidelines in Oncology (Annual Compendium)", desc: "The National Comprehensive Cancer Network's evidence-based treatment guidelines for all major cancers. The international standard for oncology practice.", price: "3999", orig: "5499", cat: "Oncology", slug: "oncology", brand: "NCCN", rating: "4.9", reviews: 654, tags: ["NCCN", "oncology guidelines"], featured: false },
  { name: "Abeloff's Clinical Oncology 6th Ed", desc: "Comprehensive clinical oncology reference with an emphasis on treatment decision-making, multidisciplinary care, and palliative medicine.", price: "12999", orig: "17499", cat: "Oncology", slug: "oncology", brand: "Elsevier", rating: "4.8", reviews: 234, tags: ["Abeloff", "oncology"], featured: false },
  { name: "Hematology 7th Ed — Hoffman, Benz, Silberstein", desc: "The most comprehensive haematology reference. Covers all benign and malignant haematological conditions with updated treatment protocols.", price: "11999", orig: "15999", cat: "Oncology", slug: "oncology", brand: "Elsevier", rating: "4.8", reviews: 312, tags: ["haematology", "hematology", "oncology"], featured: false },

  // ── Anaesthesia ──────────────────────────────────────────────────
  { name: "Miller's Anaesthesia 9th Ed (2-Vol)", desc: "The definitive anaesthesiology textbook. Covers pharmacology, equipment, regional anaesthesia, paediatric anaesthesia, and critical care.", price: "16999", orig: "22999", cat: "Anaesthesia", slug: "anaesthesia", brand: "Elsevier", rating: "4.9", reviews: 432, tags: ["Miller", "anaesthesia"], featured: false },
  { name: "Morgan & Mikhail's Clinical Anaesthesiology 6th Ed", desc: "The most popular anaesthesia textbook for residents. Clear explanations of pharmacology, equipment, regional techniques, and case-based management.", price: "5999", orig: "7999", cat: "Anaesthesia", slug: "anaesthesia", brand: "McGraw-Hill", rating: "4.8", reviews: 654, tags: ["Morgan Mikhail", "anaesthesia"], featured: false },
  { name: "Stoelting's Pharmacology & Physiology in Anaesthetic Practice 5th Ed", desc: "In-depth coverage of all pharmacological agents used in anaesthesia with mechanisms, pharmacokinetics, and clinical applications.", price: "6999", orig: "9499", cat: "Anaesthesia", slug: "anaesthesia", brand: "Wolters Kluwer", rating: "4.8", reviews: 312, tags: ["Stoelting", "anaesthesia pharmacology"], featured: false },

  // ── Orthopaedics ─────────────────────────────────────────────────
  { name: "Campbell's Operative Orthopaedics 14th Ed (5-Vol)", desc: "The comprehensive orthopaedic surgery reference. 5-volume set covering all subspecialties — arthroplasty, spine, sports medicine, tumours, and paediatric orthopaedics.", price: "24999", orig: "31999", cat: "Orthopaedics", slug: "orthopaedic", brand: "Elsevier", rating: "4.9", reviews: 312, tags: ["Campbell", "orthopaedics"], featured: false },
  { name: "Apley & Solomon's Orthopaedics & Fractures 10th Ed", desc: "The classic orthopaedics and trauma textbook. Systematic coverage of fractures, joint diseases, spine conditions, and tumours with excellent clinical photographs.", price: "4499", orig: "5999", cat: "Orthopaedics", slug: "orthopaedic", brand: "CRC Press", rating: "4.8", reviews: 1234, tags: ["Apley Solomon", "orthopaedics", "fractures"], featured: false },
  { name: "Maheshwari Essential Orthopaedics 6th Ed (Indian Ed)", desc: "The most popular orthopaedics textbook for Indian MBBS and MS students. Exam-focused, comprehensive coverage with photographs and clinical case studies.", price: "999", orig: "1399", cat: "Orthopaedics", slug: "orthopaedic", brand: "Mehta Publishers", rating: "4.8", reviews: 3456, tags: ["Maheshwari", "orthopaedics", "India"], featured: true },
  { name: "Rockwood & Green's Fractures in Adults 9th Ed (3-Vol)", desc: "The definitive fracture management reference. Covers classification, biomechanics, operative and non-operative treatment of all adult fractures.", price: "19999", orig: "26999", cat: "Orthopaedics", slug: "orthopaedic", brand: "Wolters Kluwer", rating: "4.9", reviews: 345, tags: ["Rockwood Green", "fractures"], featured: false },

  // ── Psychiatry ───────────────────────────────────────────────────
  { name: "Kaplan & Sadock's Comprehensive Textbook of Psychiatry 11th Ed (2-Vol)", desc: "The most comprehensive psychiatry reference. Covers neuroscience, psychopathology, all psychiatric disorders, and treatment modalities.", price: "19999", orig: "26999", cat: "Psychiatry", slug: "psychiatry", brand: "Wolters Kluwer", rating: "4.9", reviews: 321, tags: ["Kaplan Sadock", "psychiatry"], featured: false },
  { name: "DSM-5-TR Diagnostic & Statistical Manual — Text Revision", desc: "The authoritative psychiatric diagnostic manual with updated diagnostic criteria, clinical decision trees, and epidemiological data for all mental disorders.", price: "4999", orig: "6499", cat: "Psychiatry", slug: "psychiatry", brand: "APA", rating: "4.9", reviews: 1087, tags: ["DSM-5", "psychiatry", "diagnostic"], featured: false },
  { name: "Ahuja Textbook of Postgraduate Psychiatry 3rd Ed", desc: "The comprehensive Indian psychiatry postgraduate textbook. Covers all psychiatric disorders with Indian epidemiology, ICD-11, and NIMHANS protocols.", price: "2999", orig: "3999", cat: "Psychiatry", slug: "psychiatry", brand: "Jaypee Brothers", rating: "4.7", reviews: 876, tags: ["Ahuja", "psychiatry", "India"], featured: false },
  { name: "ICD-11 Clinical Descriptions & Diagnostic Guidelines (WHO)", desc: "WHO's International Classification of Diseases 11th Revision. Diagnostic guidelines for all mental and behavioural disorders aligned with global standards.", price: "1999", orig: "2699", cat: "Psychiatry", slug: "psychiatry", brand: "WHO Press", rating: "4.8", reviews: 654, tags: ["ICD-11", "WHO", "psychiatry"], featured: false },

  // ── Urology ──────────────────────────────────────────────────────
  { name: "Campbell-Walsh-Wein Urology 12th Ed (3-Vol)", desc: "The definitive urology reference. Covers endourology, urologic oncology, reconstructive urology, female urology, and paediatric urology.", price: "22999", orig: "29999", cat: "Urology", slug: "urology", brand: "Elsevier", rating: "4.9", reviews: 234, tags: ["Campbell Walsh Wein", "urology"], featured: false },
  { name: "EAU Guidelines on Urological Infections 2024", desc: "European Association of Urology guidelines for UTI, prostatitis, STIs, and catheter-associated infections. Essential pocket reference for urologists.", price: "1299", orig: "1799", cat: "Urology", slug: "urology", brand: "EAU", rating: "4.8", reviews: 543, tags: ["EAU", "urology guidelines", "UTI"], featured: false },

  // ── Physiotherapy ─────────────────────────────────────────────────
  { name: "Kisner & Colby Therapeutic Exercise 7th Ed", desc: "The classic evidence-based physiotherapy exercise textbook. Comprehensive musculoskeletal rehabilitation, neuromuscular re-education, and therapeutic exercise principles.", price: "5499", orig: "7499", cat: "Physiotherapy", slug: "physiotherapy", brand: "F.A. Davis", rating: "4.8", reviews: 432, tags: ["Kisner Colby", "physiotherapy"], featured: false },
  { name: "Brunnstrom's Clinical Kinesiology 6th Ed", desc: "The authoritative kinesiology and biomechanics text. Human movement science applied to physiotherapy practice, musculoskeletal assessment, and rehabilitation.", price: "3999", orig: "5499", cat: "Physiotherapy", slug: "physiotherapy", brand: "F.A. Davis", rating: "4.7", reviews: 345, tags: ["Brunnstrom", "kinesiology", "physiotherapy"], featured: false },

  // ── NEET-PG / PGMEE Preparation ──────────────────────────────────
  { name: "NEET-PG Grand Test Series 2026 (30 Mock Tests)", desc: "30 full-length computer-based mock tests with detailed explanations, previous year questions, and subject-wise performance analytics for NEET-PG 2026.", price: "3499", orig: "4999", cat: "Books & Study Material", slug: "books", brand: "DAMS", rating: "4.8", reviews: 2341, tags: ["NEET-PG", "mock test", "PGMEE"], featured: true },
  { name: "Across (All India 2500 Solved Papers) NEET-PG 2025", desc: "Comprehensive solved papers from all India medical PG entrance exams since 2000. Subject-wise distribution with detailed explanations and updated answers.", price: "2999", orig: "3999", cat: "Books & Study Material", slug: "books", brand: "DAMS", rating: "4.7", reviews: 1876, tags: ["NEET-PG", "solved papers", "PGMEE"], featured: false },
  { name: "Recall (AIIMS/PGI Questions) — Last 12 Years", desc: "Complete recalled questions from AIIMS and PGI entrance exams. Detailed explanations and high-yield clinical pearls for each question.", price: "1999", orig: "2699", cat: "Books & Study Material", slug: "books", brand: "Jaypee Brothers", rating: "4.7", reviews: 1654, tags: ["AIIMS", "PGI", "recall", "PGMEE"], featured: false },
  { name: "Mudit Khanna DNB CET Solved Papers (10 Years)", desc: "All DNB CET and FMGE solved questions with explanations. Comprehensive coverage of NBE exam pattern and frequently tested topics.", price: "1799", orig: "2399", cat: "Books & Study Material", slug: "books", brand: "CBS Publishers", rating: "4.6", reviews: 1234, tags: ["DNB", "FMGE", "NBE", "PG entrance"], featured: false },
  { name: "First Aid for USMLE Step 1 2024 Edition", desc: "The indispensable guide for USMLE Step 1. Condensed, high-yield facts, mnemonics, and clinical correlations mapped to the NBME blueprint.", price: "3999", orig: "4999", cat: "Books & Study Material", slug: "books", brand: "McGraw-Hill", rating: "4.9", reviews: 3456, tags: ["First Aid", "USMLE Step 1", "USMLE"], featured: true },
  { name: "Pathoma Fundamentals of Pathology (Dr. Husain Sattar)", desc: "The highest-yield pathology review for USMLE Step 1. Clear diagrams, concise explanations, and systems-based approach loved by medical students worldwide.", price: "2499", orig: "3299", cat: "Books & Study Material", slug: "books", brand: "Pathoma LLC", rating: "4.9", reviews: 2876, tags: ["Pathoma", "pathology", "USMLE Step 1"], featured: false },
  { name: "Sketchy Pharmacology Illustrated Reference Cards", desc: "Illustrated pharmacology mnemonics reference card set based on the Sketchy methodology. High-yield drug mechanisms, clinical pearls, and associations.", price: "1999", orig: "2699", cat: "Books & Study Material", slug: "books", brand: "Sketchy Medical", rating: "4.8", reviews: 1234, tags: ["Sketchy", "pharmacology", "USMLE"], featured: false },
];

async function seedBooks() {
  console.log(`Preparing to insert ${books.length} medical books...`);
  let inserted = 0;
  let skipped = 0;

  for (const b of books) {
    // Skip if a product with the same name already exists
    const existing = await db
      .select({ id: productsTable.id })
      .from(productsTable)
      .where(ilike(productsTable.name, b.name))
      .limit(1);

    if (existing.length > 0) {
      skipped++;
      continue;
    }

    await db.insert(productsTable).values({
      name: b.name,
      description: b.desc,
      price: b.price,
      originalPrice: b.orig ?? null,
      category: b.cat,
      categorySlug: b.slug,
      brand: b.brand,
      imageUrl: img(inserted),
      rating: b.rating,
      reviewCount: b.reviews,
      inStock: true,
      tags: b.tags,
      featured: b.featured ?? false,
    });
    inserted++;
    console.log(`  ✓ ${b.name}`);
  }

  console.log(`\nDone! Inserted: ${inserted}, Skipped (already exists): ${skipped}`);
  process.exit(0);
}

seedBooks().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
