kind = "web"
previewPath = "/"
title = "AETHEX - Medical Store"
version = "1.0.0"
id = "artifacts/aethex"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24237

[services.development]
run = "pnpm --filter @workspace/aethex run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/aethex", "run", "build" ]
publicDir = "artifacts/aethex/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24237"
BASE_PATH = "/"
